version: "3.7"
services:

  db:
    image: mariadb
    container_name: teamspeak_db
    restart: unless-stopped
    volumes:
      - "db:/var/lib/mysql"
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
    env_file: .env

  teamspeak:
    image: carlgo11/teamspeak
    container_name: teamspeak_server
    restart: unless-stopped
    env_file: .env
    ports:
      - "9987:9987/udp" # VOIP
      - "30033:30033" # File Transfer
    volumes:
      - "./ts3server_config.ini:/teamspeak/ts3server.ini:ro"
      - "files:/teamspeak/files"
    tmpfs: "/teamspeak:exec,uid=1000,mode=700"

volumes:
  db:
  files:
