version: "3.2"
services:
  teamspeak:
    image: carlgo11/teamspeak
    ports:
    - "9987:9987/udp" # VOIP
    - "30033:30033/tcp" # File Transfer
    volumes:
    - ./ts3server_config.ini:/teamspeak/ts3server.ini:ro
    - ./ts3server.sqlitedb:/teamspeak/ts3server.sqlitedb
    - ./files/:/teamspeak/files
    restart: always
